apiVersion: v1
kind: Service
metadata:
  name: postgres-primary-router
spec:
  selector:
    postgres-operator.crunchydata.com/role: master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
